name: Use the Composite Action with Actions

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Do anything else
        run: echo "Pretend to do other things" 

      # Uses the Composite Action
      - name: Build and Push the image
        uses: ./
        
